[package]
name = "icey_pudding"
version = "0.1.0"
edition = "2018"
authors = ["Nanai10a (github.com/Nanai10a)"]

[dependencies]
mongodb = "2.0.0"
clap = "3.0.0-beta.4"
serde_json = "1.0.68"
async-trait = "0.1.51"
async-recursion = "0.3.2"
chrono = "0.4.19"
smallvec = "1.6.1"
anyhow = "1.0.44"
regex = "1.5.5"
shell-words = "1.0.0"
tracing = "0.1.28"
tracing-subscriber = "0.2.23"

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = [
  "builder",
  "cache",
  "client",
  "gateway",
  "model",
  "http",
  "utils",
  "rustls_backend",
]

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.tokio]
version = "1.13.1"
features = ["full"]

[dependencies.uuid]
version = "0.8.2"
features = ["v4", "serde"]

[dependencies.range_parser]
git = "https://github.com/Nanai10a/range_parser"
