[package]
name = "icey_pudding"
version = "0.1.0-alpha.2"
edition = "2018"

[dependencies]
tokio = { version = "1.7.1", features = ["full"] }
serenity = { version = "0.10.8", default-features = false, features = ["builder", "cache", "client", "gateway", "model", "http", "utils", "rustls_backend"] }
anyhow = "1.0.41"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
chrono = "0.4.19"
regex = "1.5.4"
serde_json = "1.0.64"
clap = { version = "2.33.3", features = ["yaml"] }
yaml-rust = "0.3.5" # dependent to clap
consts = { git = "https://github.com/Nanai10a/consts" }
shell-words = "1.0.0"
mongodb = "2.0.0-beta.3"
serde = { version = "1.0.126", features = ["derive"] }
async-trait = "0.1.51"
range_parser = { git = "https://github.com/Nanai10a/range_parser" }
lazy_static = "1.4.0"
