[package]
name = "icey_pudding"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serenity = { version = "*", features = ["unstable_discord_api"] }
anyhow = "*"
uuid = "*"
chrono = "*"
