name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true

    - uses: actions-rs/clippy-check@v1.0.7
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -v --all-features

    - run: cargo build -v --release

    - run: cargo test -v
